export const CHANGE_LOADING_STATUS = "CHANGE_LOADING_STATUS";
export const CHANGE_THEME = "CHANGE_THEME";
export const CHANGE_VISIBLE_STATUS = "CHANGE_VISIBLE_STATUS";
export const CHANGE_ACTIVE_STATUS = "CHANGE_ACTIVE_STATUS";
